#!/bin/bash
GENERATE_SCRIPT='../fullauto-setup.sh'
NGINX_DEPLOY_DIR='/etc/nginx/conf.d/handson-test'
NGINX_CONF_NAME='websv.conf'

SCRIPT_DIR=$(dirname "$0")
pushd "${SCRIPT_DIR}" >/dev/null
echo "Generate start"

cat << 'EOF' > ${GENERATE_SCRIPT}
#!/bin/bash
# This script is generated by auto-script-generator.sh
EOF
echo "" >> ${GENERATE_SCRIPT}

echo "DEPLOY_DIR='${NGINX_DEPLOY_DIR}'" >> ${GENERATE_SCRIPT}
echo "CONF_NAME='${NGINX_CONF_NAME}'" >> ${GENERATE_SCRIPT}
echo "" >> ${GENERATE_SCRIPT}

cat << 'EOF' >> ${GENERATE_SCRIPT}
echo "--- Starting Nginx setup ---"
SCRIPT_DIR=$(dirname "$0")
pushd "${SCRIPT_DIR}" >/dev/null
apt update && apt install -y nginx
systemctl stop nginx
EOF
echo "" >> ${GENERATE_SCRIPT}

cat << 'EOF' >> ${GENERATE_SCRIPT}
echo "--- Creating deployment directory ---"
[ -d ${DEPLOY_DIR} ] && rm -rf ${DEPLOY_DIR}
mkdir -p ${DEPLOY_DIR}
EOF
echo "" >> ${GENERATE_SCRIPT}

echo "" >> ${GENERATE_SCRIPT}
echo "" >> ${GENERATE_SCRIPT}



echo 'echo "--- Writing config ---"' >> ${GENERATE_SCRIPT}
echo 'cat << "EOF" > ${DEPLOY_DIR}/${CONF_NAME}' >> ${GENERATE_SCRIPT}
sed "s@PLEASE_REPLACE_DEPLOY_DIR@${NGINX_DEPLOY_DIR}@g" ./${NGINX_CONF_NAME} >> ${GENERATE_SCRIPT}
echo "EOF" >> ${GENERATE_SCRIPT}
echo "" >> ${GENERATE_SCRIPT}

echo 'echo "--- Writing index.html ---"' >> ${GENERATE_SCRIPT}
echo 'cat << "EOF" > ${DEPLOY_DIR}/index.html' >> ${GENERATE_SCRIPT}
cat ./index.html >> ${GENERATE_SCRIPT}
echo "EOF" >> ${GENERATE_SCRIPT}
echo "" >> ${GENERATE_SCRIPT}

echo 'echo "--- Writing error.html ---"' >> ${GENERATE_SCRIPT}
echo 'cat << "EOF" > ${DEPLOY_DIR}/error.html' >> ${GENERATE_SCRIPT}
cat ./error.html >> ${GENERATE_SCRIPT}
echo "EOF" >> ${GENERATE_SCRIPT}
echo "" >> ${GENERATE_SCRIPT}



echo "" >> ${GENERATE_SCRIPT}
echo "" >> ${GENERATE_SCRIPT}

cat << 'EOF' >> ${GENERATE_SCRIPT}
echo "--- Setting up symbolic links and services ---"
[ -L /etc/nginx/conf.d/${CONF_NAME} ] && unlink /etc/nginx/conf.d/${CONF_NAME}
ln -s ${DEPLOY_DIR}/${CONF_NAME} /etc/nginx/conf.d/${CONF_NAME}
find /etc/nginx/sites-enabled -type l -delete
systemctl enable --now nginx
popd >/dev/null
EOF

echo ""
echo ""
echo ""
echo ""
echo ""
echo "Generate finish"
popd >/dev/null