#!/bin/bash
DEPLOY_SCRIPT='fullauto-setup.sh'

cat << 'EOF' > ${DEPLOY_SCRIPT}
#!/bin/bash
# This script is generated by generate_deploy.sh

DEPLOY_DIR='/etc/nginx/conf.d/handson-test-html'
CONF_NAME='handson-test.conf'

echo "--- Starting Nginx setup ---"
apt update && apt install -y nginx
systemctl stop nginx

echo "--- Creating deployment directory ---"
[ -d ${DEPLOY_DIR} ] && rm -rf ${DEPLOY_DIR}
mkdir -p ${DEPLOY_DIR}
EOF
echo "" >> ${DEPLOY_SCRIPT}
echo "" >> ${DEPLOY_SCRIPT}
echo "" >> ${DEPLOY_SCRIPT}



echo 'echo "--- Writing handson-test.conf ---"' >> ${DEPLOY_SCRIPT}
echo 'cat << "EOF" > ${DEPLOY_DIR}/${CONF_NAME}' >> ${DEPLOY_SCRIPT}
cat handson-test.conf >> ${DEPLOY_SCRIPT}
echo "EOF" >> ${DEPLOY_SCRIPT}
echo "" >> ${DEPLOY_SCRIPT}

echo 'echo "--- Writing index.html ---"' >> ${DEPLOY_SCRIPT}
echo 'cat << "EOF" > ${DEPLOY_DIR}/index.html' >> ${DEPLOY_SCRIPT}
cat index.html >> ${DEPLOY_SCRIPT}
echo "EOF" >> ${DEPLOY_SCRIPT}
echo "" >> ${DEPLOY_SCRIPT}

echo 'echo "--- Writing error.html ---"' >> ${DEPLOY_SCRIPT}
echo 'cat << "EOF" > ${DEPLOY_DIR}/error.html' >> ${DEPLOY_SCRIPT}
cat error.html >> ${DEPLOY_SCRIPT}
echo "EOF" >> ${DEPLOY_SCRIPT}
echo "" >> ${DEPLOY_SCRIPT}



echo "" >> ${DEPLOY_SCRIPT}
echo "" >> ${DEPLOY_SCRIPT}
cat << 'EOF' >> ${DEPLOY_SCRIPT}
echo "--- Setting up symbolic links and services ---"
ln -sf ${DEPLOY_DIR}/${CONF_NAME} /etc/nginx/conf.d/${CONF_NAME}
rm -f /etc/nginx/sites-enabled/default
systemctl enable --now nginx
EOF

chmod +x ${DEPLOY_SCRIPT}
echo "Generated ${DEPLOY_SCRIPT}"
